openapi: 3.2.0
info:
  title: CMS Common Facility Claim Status Code APIs API
  description: MicroService that contains CMS related information
  contact:
    name: Ken Kracker
    email: ken.kracker@optum.com
  version: v1.0
servers:
- url: /v1/cmscommonms
tags:
- name: Claim Status Code APIs
paths:
  /api/cms/facility/claim-status-codes:
    get:
      tags:
      - Claim Status Code APIs
      summary: Fetches the claim status codes
      operationId: getClaimStatusCode
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 1
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 50
      - name: sort
        in: query
        description: Any of these values (code, -code)are allowed.
        required: false
        schema:
          type: array
          items:
            type: string
          default:
          - code
      - name: filter
        in: query
        required: false
        schema:
          type: string
      - name: yyyy-MM-dd
        in: header
        description: Date for which historical data is required
        required: false
        schema:
          type: string
          format: yyyy-MM-dd
      responses:
        '200':
          description: Fetches the claim status codes
          content:
            application/json:
              example:
                content:
                - code: '0'
                  description: 'Cannot provide further status electronically. Note: New as of: 01/01/1995'
                - code: '1'
                  description: 'For more detailed information, see remittance advice. Note: New as of: 01/01/1995'
                - code: '100'
                  description: 'Pre-certification penalty taken. Note: New as of: 01/01/1995'
                totalCount: 3
        '400':
          description: 'Bad request: Some parameters were invalid'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'
              example:
                error:
                - sort parameter value should be from list of [code]
                warning: null
                info: null
        '500':
          description: Interal server error
          content:
            application/json:
              example:
                timestamp: '2023-10-27T08:10:07.573+00:00'
                status: 500
                error: Internal Server Error
                message: 'Request processing failed: java.lang.IllegalArgumentException: Page size must not be less than one'
                path: /cmscommonms/api/cms/claim-status-codes
      security:
      - bearerAuth: []
components:
  schemas:
    Notification:
      type: object
      properties:
        error:
          type: array
          items:
            type: string
        warning:
          type: array
          items:
            type: string
        info:
          type: array
          items:
            type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
x-readme:
  explorer-enabled: true
  proxy-enabled: true
