openapi: 3.2.0
info:
  title: Optum Common Facility Provider Lookup APIs API
  description: MicroService that contains Optum module-related information
  contact:
    name: Ken Kracker
    email: ken.kracker@optum.com
  version: v1.0
servers:
- url: /v1/optumcommonms
tags:
- name: Provider Lookup APIs
paths:
  /api/optum/facility/provider-lookup/{careSetting}:
    get:
      tags:
      - Provider Lookup APIs
      summary: Fetches outpatient provider lookup table data
      operationId: getLookupTableData
      parameters:
      - name: careSetting
        in: path
        required: true
        schema:
          type: string
          enum:
          - outpatient
          - inpatient
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 1
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 50
      - name: sort
        in: query
        description: Any of these values (providerNumber,-providerNumber) are allowed.
        required: false
        schema:
          type: array
          items:
            type: string
          default:
          - providerNumber
      - name: filter
        in: query
        required: false
        schema:
          type: string
      - name: yyyy-MM-dd
        in: header
        description: Date for which historical data is required
        required: false
        schema:
          type: string
          format: yyyy-MM-dd
      responses:
        '200':
          description: Fetch columns for lookup table
          content:
            application/json:
              example:
                content:
                - providerNumber: '010001'
                  providerName: SOUTHEAST HEALTH MEDICAL
                  state: AL
                - providerNumber: '010005'
                  providerName: MARSHALL MEDICAL CENTERS
                  state: AL
                - providerNumber: '010006'
                  providerName: NORTH ALABAMA MEDICAL CEN
                  state: AL
                totalCount: 7005
        '400':
          description: Bad request
          content:
            application/json:
              example:
                error:
                - sort parameter value should be from list of [providerNumber, -providerNumber]
                warning: null
                info: null
        '500':
          description: Internal server error
          content:
            application/json:
              example:
                timestamp: '2023-07-27T08:10:07.573+00:00'
                status: 500
                error: Internal Server Error
                message: 'Request processing failed: java.lang.IllegalArgumentException: Page size must not be less than one'
                path: /cmscommonms/api/optum/facility/provider-lookup/outpatient
      security:
      - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
x-readme:
  explorer-enabled: true
  proxy-enabled: true
