openapi: 3.2.0
info:
  title: Optum Real-Time eContent Web services ICD9 Mapping API
  description: Optum® Real-Time eContent web services provides access to both ondemand medical coding data and Optum coding tool logic required by your applications. The information you or your clients need is delivered to your application in real time, when you need it, and customized to how you want it displayed. Optum Real-Time eContent service provides access to the content of 37 printed coding resources and proprietary data and offers the power of the Optum CodeLogic™ search engine.
  contact:
    name: Ken Kracker
    email: ken.kracker@optum.com
  version: 1.0.0
servers:
- url: sandbox-apigw.optum.com/ci/rtec/v1/ws
security:
- bearerAuth: []
tags:
- name: ICD9 Mapping
paths:
  /codetype/{codetype}/{code}/icd9mapping:
    get:
      tags:
      - ICD9 Mapping
      summary: Backward Mapping to ICD-9-CM Vol-1 or ICD-9-CM Vol-3 Codes
      operationId: getI9Mapping
      parameters:
      - name: codetype
        in: path
        description: The codetype needed to identify the type of code
        required: true
        schema:
          type: string
          enum:
          - icd10cm
          - icd10pcs
      - name: code
        in: path
        description: The code value for the respective codetype
        required: true
        schema:
          type: string
        example: F90.9
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Icd9Mapping'
              example:
                node:
                - code: '314.00'
                  desc: Attention deficit disorder of childhood without mention of hyperactivity
                  tips: GEM
                  premierPick: N
                  billTogether: N
                  href: /ws/codetype/icd9v1/314.00
                - code: '314.01'
                  desc: Attention deficit disorder of childhood with hyperactivity
                  tips: GEM
                  premierPick: Y
                  billTogether: N
                  href: /ws/codetype/icd9v1/314.01
        '400':
          description: Wrong codetype
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Icd9Mapping'
              example:
                error:
                - The code provided ('5.31') in this web service request is not a valid 'icd10pcs' code.
                warning: []
                info: []
        '401':
          description: Not Authorized
          content:
            application/json:
              example:
                timestamp: '2022-07-06T16:34:39.385Z'
                error: Unauthorized
                status: 401
        '404':
          description: Not Found - the data was not found
          content:
            application/json:
              example:
                error:
                - The requested resource does not exist.
                warning: []
                info: []
        '405':
          description: Method Not Allowed - Request method not supported
          content:
            application/json:
              example:
                timestamp: '2022-07-07T15:28:34.152Z'
                status: 405
                error: Method Not Allowed
        '503':
          description: Service Unavailable
components:
  schemas:
    Icd9Mapping:
      type: object
      properties:
        node:
          type: array
          items:
            $ref: '#/components/schemas/Icd9Code'
      xml:
        name: icd-9-mapping
    Icd9Code:
      required:
      - code
      type: object
      properties:
        code:
          type: string
        desc:
          type: string
        tips:
          type: string
        premierPick:
          type: string
          xml:
            name: premier-pick
        billTogether:
          type: string
          xml:
            name: bill-together
        href:
          type: string
          xml:
            attribute: true
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    ws_auth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://idx.linkhealth.com/auth
          tokenUrl: https://idx.linkhealth.com/auth/token
          scopes:
            scope-1: required scope for API access
x-readme:
  explorer-enabled: true
  proxy-enabled: true
