openapi: 3.2.0
info:
  title: Optum Real-Time eContent Web services Data File API
  description: Optum® Real-Time eContent web services provides access to both ondemand medical coding data and Optum coding tool logic required by your applications. The information you or your clients need is delivered to your application in real time, when you need it, and customized to how you want it displayed. Optum Real-Time eContent service provides access to the content of 37 printed coding resources and proprietary data and offers the power of the Optum CodeLogic™ search engine.
  contact:
    name: Ken Kracker
    email: ken.kracker@optum.com
  version: 1.0.0
servers:
- url: sandbox-apigw.optum.com/ci/rtec/v1/ws
security:
- bearerAuth: []
tags:
- name: Data File
paths:
  /datafile/list:
    get:
      tags:
      - Data File
      summary: Data File List
      operationId: getDatafileList
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Link'
              example:
              - href: /ws/datafile/file/optum_cpc_base_2017_07
                value: OPTUM_CPC_BASE_2017_07, Effective on 04/01/2018
              - href: /ws/datafile/file/optum_cpc_base_2017_10_update
                value: OPTUM_CPC_BASE_2017_10_update, Effective on 04/01/2018
        '401':
          description: Not Authorized
          content:
            application/json:
              example:
                timestamp: '2022-07-06T16:34:39.385Z'
                error: Unauthorized
                status: 401
        '404':
          description: Not Found - the data was not found
          content:
            application/json:
              example:
                error:
                - The requested resource does not exist.
                warning: []
                info: []
        '405':
          description: Method Not Allowed - Request method not supported
          content:
            application/json:
              example:
                timestamp: '2022-07-07T15:28:34.152Z'
                status: 405
                error: Method Not Allowed
        '503':
          description: Service Unavailable
  /datafile/file/{fileReqName}:
    get:
      tags:
      - Data File
      summary: Data File
      operationId: getFile
      parameters:
      - name: fileReqName
        in: path
        description: The name of the file
        required: true
        schema:
          type: string
        example: optum_cpc_base_2017_07
      - name: If-Modified-Since
        in: header
        description: The date last modified
        schema:
          type: string
      responses:
        '200':
          description: Successful Response
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/Response'
              example: default response
        '401':
          description: Not Authorized
          content:
            application/json:
              example:
                timestamp: '2022-07-06T16:34:39.385Z'
                error: Unauthorized
                status: 401
        '404':
          description: Not Found - the data was not found
          content:
            application/json:
              example:
                error:
                - The requested resource does not exist.
                warning: []
                info: []
        '405':
          description: Method Not Allowed - Request method not supported
          content:
            application/json:
              example:
                timestamp: '2022-07-07T15:28:34.152Z'
                status: 405
                error: Method Not Allowed
        '503':
          description: Service Unavailable
components:
  schemas:
    MediaType:
      type: object
      properties:
        type:
          type: string
        subtype:
          type: string
        parameters:
          type: object
          additionalProperties:
            type: string
        wildcardType:
          type: boolean
        wildcardSubtype:
          type: boolean
    Link:
      type: object
      properties:
        href:
          type: string
          xml:
            attribute: true
        value:
          type: string
    EntityTag:
      type: object
      properties:
        value:
          type: string
        weak:
          type: boolean
    NewCookie:
      type: object
      properties:
        name:
          type: string
        value:
          type: string
        version:
          type: integer
          format: int32
        path:
          type: string
        domain:
          type: string
        comment:
          type: string
        maxAge:
          type: integer
          format: int32
        expiry:
          type: string
          format: date-time
        secure:
          type: boolean
        httpOnly:
          type: boolean
        sameSite:
          type: string
          enum:
          - NONE
          - LAX
          - STRICT
    Response:
      type: object
      properties:
        entityTag:
          $ref: '#/components/schemas/EntityTag'
        mediaType:
          $ref: '#/components/schemas/MediaType'
        metadata:
          type: object
          properties:
            empty:
              type: boolean
          additionalProperties:
            type: array
            items:
              type: object
        length:
          type: integer
          format: int32
        location:
          type: string
          format: uri
        language:
          type: object
          properties:
            language:
              type: string
            displayName:
              type: string
            country:
              type: string
            variant:
              type: string
            script:
              type: string
            unicodeLocaleAttributes:
              uniqueItems: true
              type: array
              items:
                type: string
            unicodeLocaleKeys:
              uniqueItems: true
              type: array
              items:
                type: string
            displayLanguage:
              type: string
            displayScript:
              type: string
            displayCountry:
              type: string
            displayVariant:
              type: string
            extensionKeys:
              uniqueItems: true
              type: array
              items:
                type: string
            iso3Language:
              type: string
            iso3Country:
              type: string
        date:
          type: string
          format: date-time
        lastModified:
          type: string
          format: date-time
        headers:
          type: object
          properties:
            empty:
              type: boolean
          additionalProperties:
            type: array
            items:
              type: object
        closed:
          type: boolean
        status:
          type: integer
          format: int32
        entity:
          type: object
        links:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/Link'
        cookies:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/NewCookie'
        allowedMethods:
          uniqueItems: true
          type: array
          items:
            type: string
        statusInfo:
          $ref: '#/components/schemas/StatusType'
        stringHeaders:
          type: object
          properties:
            empty:
              type: boolean
          additionalProperties:
            type: array
            items:
              type: string
    StatusType:
      type: object
      properties:
        reasonPhrase:
          type: string
        family:
          type: string
          enum:
          - INFORMATIONAL
          - SUCCESSFUL
          - REDIRECTION
          - CLIENT_ERROR
          - SERVER_ERROR
          - OTHER
        statusCode:
          type: integer
          format: int32
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    ws_auth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://idx.linkhealth.com/auth
          tokenUrl: https://idx.linkhealth.com/auth/token
          scopes:
            scope-1: required scope for API access
x-readme:
  explorer-enabled: true
  proxy-enabled: true
