openapi: 3.2.0
info:
  title: Optum Common Facility Wage Index API
  description: MicroService that contains Optum module-related information
  contact:
    name: Ken Kracker
    email: ken.kracker@optum.com
  version: v1.0
servers:
- url: /v1/optumcommonms
tags:
- name: Wage Index API
paths:
  /api/optum/facility/wage-index:
    get:
      tags:
      - Wage Index API
      summary: Fetches wage index list
      operationId: getWageIndexList
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 1
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 50
      - name: filter
        in: query
        description: Filter considers provider number and provider name, The provider number will be start match and provider name will be any match
        required: false
        schema:
          type: string
      - name: yyyy-MM-dd
        in: header
        description: Date for which historical data is required
        required: false
        schema:
          type: string
          format: yyyy-MM-dd
      responses:
        '200':
          description: Fetches wage index list
          content:
            application/json:
              example:
                content:
                - providerNumber: '010001'
                  providerName: SOUTHEAST HEALTH MEDICAL
                  state: Alabama
                  wageIndexQ1: '0.8573'
                  wageIndexQ2: '0.8573'
                  wageIndexQ3: '0.8573'
                  wageIndexQ4: '0.8573'
                  year: '2024'
                - providerNumber: '010001'
                  providerName: SOUTHEAST HEALTH MEDICAL
                  state: Alabama
                  wageIndexQ1: '0.8213'
                  wageIndexQ2: '0.8213'
                  wageIndexQ3: '0.8213'
                  year: '2023'
                totalCount: 2
        '400':
          description: Bad request
          content:
            application/json:
              example:
                error:
                - 'filter : length must be between 2 and 180'
                warning: null
                info: null
        '500':
          description: Internal server error
          content:
            application/json:
              example:
                timestamp: '2024-11-05T08:10:07.573+00:00'
                status: 500
                error: Internal Server Error
                message: 'Request processing failed: java.lang.IllegalArgumentException: Page size must not be less than one'
                path: /optumcommonms/api/optum/facility/wage-index?page=-1
      security:
      - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
x-readme:
  explorer-enabled: true
  proxy-enabled: true
