generated: '2026-08-14'
method: probed
source: live DNS/TLS/HTTP probes of apis.yml + OpenAPI hosts
hosts:
- host: www.optum.com
  https: true
  tls_version: TLSv1.3
  cert_expires: Dec  2 23:59:59 2026 GMT
  hsts: true
  hsts_max_age: 300
- host: developer.optum.com
  https: true
  tls_version: TLSv1.3
  cert_expires: Oct 25 12:43:52 2026 GMT
  hsts: null
- host: apigw.optum.com
  https: true
  tls_version: TLSv1.3
  cert_expires: Nov  5 05:03:48 2026 GMT
  hsts: true
  hsts_max_age: 15552000
domains:
- domain: optum.com
  dnssec: true
  caa:
  - 0 issuemail "sectigo.com"
  spf: true
  dmarc: true
  dmarc_policy: reject
